In [1]:
%load_ext kedro.ipython

[03/20/26 14:10:41] INFO     Using                                                                  ]8;id=884033;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=135978;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\framework\project\__init__.py#269\269]8;;\
                             'C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\framework
                             \project\rich_logging.yml' as logging configuration.

[03/20/26 14:10:42] INFO     Registered line magic '%reload_kedro'                                   ]8;id=201279;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=972534;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\ipython\__init__.py#64\64]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=959781;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=476474;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\ipython\__init__.py#66\66]8;;\

                    INFO     Resolved project path as:                                              ]8;id=46288;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=238916;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\ipython\__init__.py#181\181]8;;\
                             C:\Users\pc\mi-proyecto-kedro\proyecto-simple.
                             To set a different path, run '%reload_kedro <project_root>'

[03/20/26 14:11:28] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=890232;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=239829;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro_telemetry\plugin.py#242\242]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

[03/20/26 14:11:29] INFO     Kedro project proyecto-simple                                          ]8;id=256657;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=872121;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\ipython\__init__.py#147\147]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=292562;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=789973;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\ipython\__init__.py#148\148]8;;\
                             'pipelines'

[03/20/26 14:11:32] INFO     Registered line magic 'run_viz'                                        ]8;id=364696;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=155422;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\ipython\__init__.py#154\154]8;;\

In [2]:
catalog.keys()

[
    'companies',
    'reviews',
    'shuttles',
    'preprocessed_companies',
    'preprocessed_shuttles',
    'model_input_table',
    'regressor',
    'shuttle_passenger_capacity_plot_exp',
    'shuttle_passenger_capacity_plot_go',
    'dummy_confusion_matrix',
    'parameters',
    'params:model_options',
    'params:model_options.test_size',
    'params:model_options.random_state',
    'params:model_options.features'
]

In [3]:
companies = catalog.load("companies")

[03/20/26 14:12:26] INFO     Loading data from companies (CSVDataset)...                       ]8;id=200871;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=744034;file://C:\Users\pc\mi-proyecto-kedro\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

In [4]:
companies['iata_approved'].describe()

count     10017
unique        2
top           f
freq       6001
Name: iata_approved, dtype: object

In [5]:
def is_true(x):
    return x == "t"
x='f'
is_true(x)

False

In [6]:
companies['iata_approved'].dtype

dtype('O')

In [7]:
companies

,id,company_rating,company_location,total_fleet_count,iata_approved
0,3888,100%,Isle of Man,1.0,f
1,46728,100%,NaN,1.0,f
2,34618,38%,Isle of Man,1.0,f
3,28619,100%,Bosnia and Herzegovina,1.0,f
4,8240,NaN,Chile,1.0,t
...,...,...,...,...,...
10014,20213,NaN,Russian Federation,1.0,f
10015,2235,100%,Guinea,1.0,f
10016,2353,100%,Senegal,2.0,t
10017,49772,100%,Jersey,1.0,f
10018,16548,90%,NaN,2.0,f

In [8]:
companies['iata_approved'].dtype

dtype('O')

In [9]:
is_true(companies['iata_approved'])

0        False
1        False
2        False
3        False
4         True
         ...
10014    False
10015    False
10016     True
10017    False
10018    False
Name: iata_approved, Length: 10019, dtype: bool

In [10]:
import pandas as pd

In [13]:
def is_true(x: pd.Series) -> pd.Series:
    return x == "t"

In [14]:
x = 'f'
is_true(x)

False

In [15]:
def parse_percentage(x: pd.Series) -> pd.Series:
    x = x.str.replace("%","")
    x = x.astype(float) / 100
    return x

In [17]:
parse_percentage(companies['company_rating'])

0        1.00
1        1.00
2        0.38
3        1.00
4         NaN
         ...
10014     NaN
10015    1.00
10016    1.00
10017    1.00
10018    0.90
Name: company_rating, Length: 10019, dtype: float64

In [20]:
def preprocess_companies(companies: pd.DataFrame) -> pd.DataFrame:
    """Preprocesses the data for companies.

    Args:
        companies: Raw data.
    Returns:
        Preprocessed data, with `company_rating` converted to a float and
        `iata_approved` converted to boolean.
    """
    companies["iata_approved"] = is_true(companies["iata_approved"])
    companies["company_rating"] = parse_percentage(companies["company_rating"])
    return companies

In [22]:
preprocess_companies(companies)

,id,company_rating,company_location,total_fleet_count,iata_approved
0,3888,1.00,Isle of Man,1.0,False
1,46728,1.00,NaN,1.0,False
2,34618,0.38,Isle of Man,1.0,False
3,28619,1.00,Bosnia and Herzegovina,1.0,False
4,8240,NaN,Chile,1.0,True
...,...,...,...,...,...
10014,20213,NaN,Russian Federation,1.0,False
10015,2235,1.00,Guinea,1.0,False
10016,2353,1.00,Senegal,2.0,True
10017,49772,1.00,Jersey,1.0,False
10018,16548,0.90,NaN,2.0,False